// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)
