// Code generated by entc, DO NOT EDIT.

package office

import (
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team09/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Officename applies equality check predicate on the "officename" field. It's identical to OfficenameEQ.
func Officename(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOfficename), v))
	})
}

// Roomnumber applies equality check predicate on the "roomnumber" field. It's identical to RoomnumberEQ.
func Roomnumber(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRoomnumber), v))
	})
}

// Doctoridcard applies equality check predicate on the "doctoridcard" field. It's identical to DoctoridcardEQ.
func Doctoridcard(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDoctoridcard), v))
	})
}

// AddedTime1 applies equality check predicate on the "added_time1" field. It's identical to AddedTime1EQ.
func AddedTime1(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAddedTime1), v))
	})
}

// AddedTime2 applies equality check predicate on the "added_time2" field. It's identical to AddedTime2EQ.
func AddedTime2(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAddedTime2), v))
	})
}

// OfficenameEQ applies the EQ predicate on the "officename" field.
func OfficenameEQ(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOfficename), v))
	})
}

// OfficenameNEQ applies the NEQ predicate on the "officename" field.
func OfficenameNEQ(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOfficename), v))
	})
}

// OfficenameIn applies the In predicate on the "officename" field.
func OfficenameIn(vs ...string) predicate.Office {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldOfficename), v...))
	})
}

// OfficenameNotIn applies the NotIn predicate on the "officename" field.
func OfficenameNotIn(vs ...string) predicate.Office {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldOfficename), v...))
	})
}

// OfficenameGT applies the GT predicate on the "officename" field.
func OfficenameGT(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldOfficename), v))
	})
}

// OfficenameGTE applies the GTE predicate on the "officename" field.
func OfficenameGTE(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldOfficename), v))
	})
}

// OfficenameLT applies the LT predicate on the "officename" field.
func OfficenameLT(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldOfficename), v))
	})
}

// OfficenameLTE applies the LTE predicate on the "officename" field.
func OfficenameLTE(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldOfficename), v))
	})
}

// OfficenameContains applies the Contains predicate on the "officename" field.
func OfficenameContains(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldOfficename), v))
	})
}

// OfficenameHasPrefix applies the HasPrefix predicate on the "officename" field.
func OfficenameHasPrefix(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldOfficename), v))
	})
}

// OfficenameHasSuffix applies the HasSuffix predicate on the "officename" field.
func OfficenameHasSuffix(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldOfficename), v))
	})
}

// OfficenameEqualFold applies the EqualFold predicate on the "officename" field.
func OfficenameEqualFold(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldOfficename), v))
	})
}

// OfficenameContainsFold applies the ContainsFold predicate on the "officename" field.
func OfficenameContainsFold(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldOfficename), v))
	})
}

// RoomnumberEQ applies the EQ predicate on the "roomnumber" field.
func RoomnumberEQ(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRoomnumber), v))
	})
}

// RoomnumberNEQ applies the NEQ predicate on the "roomnumber" field.
func RoomnumberNEQ(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRoomnumber), v))
	})
}

// RoomnumberIn applies the In predicate on the "roomnumber" field.
func RoomnumberIn(vs ...string) predicate.Office {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRoomnumber), v...))
	})
}

// RoomnumberNotIn applies the NotIn predicate on the "roomnumber" field.
func RoomnumberNotIn(vs ...string) predicate.Office {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRoomnumber), v...))
	})
}

// RoomnumberGT applies the GT predicate on the "roomnumber" field.
func RoomnumberGT(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRoomnumber), v))
	})
}

// RoomnumberGTE applies the GTE predicate on the "roomnumber" field.
func RoomnumberGTE(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRoomnumber), v))
	})
}

// RoomnumberLT applies the LT predicate on the "roomnumber" field.
func RoomnumberLT(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRoomnumber), v))
	})
}

// RoomnumberLTE applies the LTE predicate on the "roomnumber" field.
func RoomnumberLTE(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRoomnumber), v))
	})
}

// RoomnumberContains applies the Contains predicate on the "roomnumber" field.
func RoomnumberContains(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRoomnumber), v))
	})
}

// RoomnumberHasPrefix applies the HasPrefix predicate on the "roomnumber" field.
func RoomnumberHasPrefix(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRoomnumber), v))
	})
}

// RoomnumberHasSuffix applies the HasSuffix predicate on the "roomnumber" field.
func RoomnumberHasSuffix(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRoomnumber), v))
	})
}

// RoomnumberEqualFold applies the EqualFold predicate on the "roomnumber" field.
func RoomnumberEqualFold(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRoomnumber), v))
	})
}

// RoomnumberContainsFold applies the ContainsFold predicate on the "roomnumber" field.
func RoomnumberContainsFold(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRoomnumber), v))
	})
}

// DoctoridcardEQ applies the EQ predicate on the "doctoridcard" field.
func DoctoridcardEQ(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDoctoridcard), v))
	})
}

// DoctoridcardNEQ applies the NEQ predicate on the "doctoridcard" field.
func DoctoridcardNEQ(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDoctoridcard), v))
	})
}

// DoctoridcardIn applies the In predicate on the "doctoridcard" field.
func DoctoridcardIn(vs ...string) predicate.Office {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDoctoridcard), v...))
	})
}

// DoctoridcardNotIn applies the NotIn predicate on the "doctoridcard" field.
func DoctoridcardNotIn(vs ...string) predicate.Office {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDoctoridcard), v...))
	})
}

// DoctoridcardGT applies the GT predicate on the "doctoridcard" field.
func DoctoridcardGT(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDoctoridcard), v))
	})
}

// DoctoridcardGTE applies the GTE predicate on the "doctoridcard" field.
func DoctoridcardGTE(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDoctoridcard), v))
	})
}

// DoctoridcardLT applies the LT predicate on the "doctoridcard" field.
func DoctoridcardLT(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDoctoridcard), v))
	})
}

// DoctoridcardLTE applies the LTE predicate on the "doctoridcard" field.
func DoctoridcardLTE(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDoctoridcard), v))
	})
}

// DoctoridcardContains applies the Contains predicate on the "doctoridcard" field.
func DoctoridcardContains(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDoctoridcard), v))
	})
}

// DoctoridcardHasPrefix applies the HasPrefix predicate on the "doctoridcard" field.
func DoctoridcardHasPrefix(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDoctoridcard), v))
	})
}

// DoctoridcardHasSuffix applies the HasSuffix predicate on the "doctoridcard" field.
func DoctoridcardHasSuffix(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDoctoridcard), v))
	})
}

// DoctoridcardEqualFold applies the EqualFold predicate on the "doctoridcard" field.
func DoctoridcardEqualFold(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDoctoridcard), v))
	})
}

// DoctoridcardContainsFold applies the ContainsFold predicate on the "doctoridcard" field.
func DoctoridcardContainsFold(v string) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDoctoridcard), v))
	})
}

// AddedTime1EQ applies the EQ predicate on the "added_time1" field.
func AddedTime1EQ(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAddedTime1), v))
	})
}

// AddedTime1NEQ applies the NEQ predicate on the "added_time1" field.
func AddedTime1NEQ(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAddedTime1), v))
	})
}

// AddedTime1In applies the In predicate on the "added_time1" field.
func AddedTime1In(vs ...time.Time) predicate.Office {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAddedTime1), v...))
	})
}

// AddedTime1NotIn applies the NotIn predicate on the "added_time1" field.
func AddedTime1NotIn(vs ...time.Time) predicate.Office {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAddedTime1), v...))
	})
}

// AddedTime1GT applies the GT predicate on the "added_time1" field.
func AddedTime1GT(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAddedTime1), v))
	})
}

// AddedTime1GTE applies the GTE predicate on the "added_time1" field.
func AddedTime1GTE(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAddedTime1), v))
	})
}

// AddedTime1LT applies the LT predicate on the "added_time1" field.
func AddedTime1LT(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAddedTime1), v))
	})
}

// AddedTime1LTE applies the LTE predicate on the "added_time1" field.
func AddedTime1LTE(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAddedTime1), v))
	})
}

// AddedTime2EQ applies the EQ predicate on the "added_time2" field.
func AddedTime2EQ(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAddedTime2), v))
	})
}

// AddedTime2NEQ applies the NEQ predicate on the "added_time2" field.
func AddedTime2NEQ(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAddedTime2), v))
	})
}

// AddedTime2In applies the In predicate on the "added_time2" field.
func AddedTime2In(vs ...time.Time) predicate.Office {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAddedTime2), v...))
	})
}

// AddedTime2NotIn applies the NotIn predicate on the "added_time2" field.
func AddedTime2NotIn(vs ...time.Time) predicate.Office {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Office(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAddedTime2), v...))
	})
}

// AddedTime2GT applies the GT predicate on the "added_time2" field.
func AddedTime2GT(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAddedTime2), v))
	})
}

// AddedTime2GTE applies the GTE predicate on the "added_time2" field.
func AddedTime2GTE(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAddedTime2), v))
	})
}

// AddedTime2LT applies the LT predicate on the "added_time2" field.
func AddedTime2LT(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAddedTime2), v))
	})
}

// AddedTime2LTE applies the LTE predicate on the "added_time2" field.
func AddedTime2LTE(v time.Time) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAddedTime2), v))
	})
}

// HasDoctor applies the HasEdge predicate on the "doctor" edge.
func HasDoctor() predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DoctorTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DoctorTable, DoctorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDoctorWith applies the HasEdge predicate on the "doctor" edge with a given conditions (other predicates).
func HasDoctorWith(preds ...predicate.Doctor) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DoctorInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DoctorTable, DoctorColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDepartment applies the HasEdge predicate on the "department" edge.
func HasDepartment() predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DepartmentTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepartmentWith applies the HasEdge predicate on the "department" edge with a given conditions (other predicates).
func HasDepartmentWith(preds ...predicate.Department) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DepartmentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExtradoctor applies the HasEdge predicate on the "extradoctor" edge.
func HasExtradoctor() predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ExtradoctorTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ExtradoctorTable, ExtradoctorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExtradoctorWith applies the HasEdge predicate on the "extradoctor" edge with a given conditions (other predicates).
func HasExtradoctorWith(preds ...predicate.Extradoctor) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ExtradoctorInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ExtradoctorTable, ExtradoctorColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSchedules applies the HasEdge predicate on the "schedules" edge.
func HasSchedules() predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SchedulesTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SchedulesTable, SchedulesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSchedulesWith applies the HasEdge predicate on the "schedules" edge with a given conditions (other predicates).
func HasSchedulesWith(preds ...predicate.Schedule) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SchedulesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SchedulesTable, SchedulesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Office) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Office) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Office) predicate.Office {
	return predicate.Office(func(s *sql.Selector) {
		p(s.Not())
	})
}
