// Code generated by entc, DO NOT EDIT.

package extradoctor

const (
	// Label holds the string label denoting the extradoctor type in the database.
	Label = "extradoctor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSpecialname holds the string denoting the specialname field in the database.
	FieldSpecialname = "specialname"

	// EdgeSpecialdoctors holds the string denoting the specialdoctors edge name in mutations.
	EdgeSpecialdoctors = "specialdoctors"
	// EdgeOffices holds the string denoting the offices edge name in mutations.
	EdgeOffices = "offices"

	// Table holds the table name of the extradoctor in the database.
	Table = "extradoctors"
	// SpecialdoctorsTable is the table the holds the specialdoctors relation/edge.
	SpecialdoctorsTable = "specialdoctors"
	// SpecialdoctorsInverseTable is the table name for the Specialdoctor entity.
	// It exists in this package in order to avoid circular dependency with the "specialdoctor" package.
	SpecialdoctorsInverseTable = "specialdoctors"
	// SpecialdoctorsColumn is the table column denoting the specialdoctors relation/edge.
	SpecialdoctorsColumn = "extradoctor_id"
	// OfficesTable is the table the holds the offices relation/edge.
	OfficesTable = "offices"
	// OfficesInverseTable is the table name for the Office entity.
	// It exists in this package in order to avoid circular dependency with the "office" package.
	OfficesInverseTable = "offices"
	// OfficesColumn is the table column denoting the offices relation/edge.
	OfficesColumn = "extradoctor_id"
)

// Columns holds all SQL columns for extradoctor fields.
var Columns = []string{
	FieldID,
	FieldSpecialname,
}

var (
	// SpecialnameValidator is a validator for the "specialname" field. It is called by the builders before save.
	SpecialnameValidator func(string) error
)
