// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/team09/app/ent/department"
	"github.com/team09/app/ent/doctor"
	"github.com/team09/app/ent/special_doctor"
	"github.com/team09/app/ent/specialist"
)

// Special_Doctor is the model entity for the Special_Doctor schema.
type Special_Doctor struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Other holds the value of the "Other" field.
	Other string `json:"Other,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the Special_DoctorQuery when eager-loading is set.
	Edges                 Special_DoctorEdges `json:"edges"`
	department_id         *int
	special_doctor_doctor *int
	specialist_id         *int
}

// Special_DoctorEdges holds the relations/edges for other nodes in the graph.
type Special_DoctorEdges struct {
	// Doctor holds the value of the doctor edge.
	Doctor *Doctor
	// Department holds the value of the department edge.
	Department *Department
	// Specialist holds the value of the specialist edge.
	Specialist *Specialist
	// Offices holds the value of the offices edge.
	Offices []*Office
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// DoctorOrErr returns the Doctor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Special_DoctorEdges) DoctorOrErr() (*Doctor, error) {
	if e.loadedTypes[0] {
		if e.Doctor == nil {
			// The edge doctor was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: doctor.Label}
		}
		return e.Doctor, nil
	}
	return nil, &NotLoadedError{edge: "doctor"}
}

// DepartmentOrErr returns the Department value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Special_DoctorEdges) DepartmentOrErr() (*Department, error) {
	if e.loadedTypes[1] {
		if e.Department == nil {
			// The edge department was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: department.Label}
		}
		return e.Department, nil
	}
	return nil, &NotLoadedError{edge: "department"}
}

// SpecialistOrErr returns the Specialist value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Special_DoctorEdges) SpecialistOrErr() (*Specialist, error) {
	if e.loadedTypes[2] {
		if e.Specialist == nil {
			// The edge specialist was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: specialist.Label}
		}
		return e.Specialist, nil
	}
	return nil, &NotLoadedError{edge: "specialist"}
}

// OfficesOrErr returns the Offices value or an error if the edge
// was not loaded in eager-loading.
func (e Special_DoctorEdges) OfficesOrErr() ([]*Office, error) {
	if e.loadedTypes[3] {
		return e.Offices, nil
	}
	return nil, &NotLoadedError{edge: "offices"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Special_Doctor) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Other
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Special_Doctor) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // department_id
		&sql.NullInt64{}, // special_doctor_doctor
		&sql.NullInt64{}, // specialist_id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Special_Doctor fields.
func (sd *Special_Doctor) assignValues(values ...interface{}) error {
	if m, n := len(values), len(special_doctor.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	sd.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Other", values[0])
	} else if value.Valid {
		sd.Other = value.String
	}
	values = values[1:]
	if len(values) == len(special_doctor.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field department_id", value)
		} else if value.Valid {
			sd.department_id = new(int)
			*sd.department_id = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field special_doctor_doctor", value)
		} else if value.Valid {
			sd.special_doctor_doctor = new(int)
			*sd.special_doctor_doctor = int(value.Int64)
		}
		if value, ok := values[2].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field specialist_id", value)
		} else if value.Valid {
			sd.specialist_id = new(int)
			*sd.specialist_id = int(value.Int64)
		}
	}
	return nil
}

// QueryDoctor queries the doctor edge of the Special_Doctor.
func (sd *Special_Doctor) QueryDoctor() *DoctorQuery {
	return (&Special_DoctorClient{config: sd.config}).QueryDoctor(sd)
}

// QueryDepartment queries the department edge of the Special_Doctor.
func (sd *Special_Doctor) QueryDepartment() *DepartmentQuery {
	return (&Special_DoctorClient{config: sd.config}).QueryDepartment(sd)
}

// QuerySpecialist queries the specialist edge of the Special_Doctor.
func (sd *Special_Doctor) QuerySpecialist() *SpecialistQuery {
	return (&Special_DoctorClient{config: sd.config}).QuerySpecialist(sd)
}

// QueryOffices queries the offices edge of the Special_Doctor.
func (sd *Special_Doctor) QueryOffices() *OfficeQuery {
	return (&Special_DoctorClient{config: sd.config}).QueryOffices(sd)
}

// Update returns a builder for updating this Special_Doctor.
// Note that, you need to call Special_Doctor.Unwrap() before calling this method, if this Special_Doctor
// was returned from a transaction, and the transaction was committed or rolled back.
func (sd *Special_Doctor) Update() *Special_DoctorUpdateOne {
	return (&Special_DoctorClient{config: sd.config}).UpdateOne(sd)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (sd *Special_Doctor) Unwrap() *Special_Doctor {
	tx, ok := sd.config.driver.(*txDriver)
	if !ok {
		panic("ent: Special_Doctor is not a transactional entity")
	}
	sd.config.driver = tx.drv
	return sd
}

// String implements the fmt.Stringer.
func (sd *Special_Doctor) String() string {
	var builder strings.Builder
	builder.WriteString("Special_Doctor(")
	builder.WriteString(fmt.Sprintf("id=%v", sd.ID))
	builder.WriteString(", Other=")
	builder.WriteString(sd.Other)
	builder.WriteByte(')')
	return builder.String()
}

// Special_Doctors is a parsable slice of Special_Doctor.
type Special_Doctors []*Special_Doctor

func (sd Special_Doctors) config(cfg config) {
	for _i := range sd {
		sd[_i].config = cfg
	}
}
