// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team09/app/ent/doctor"
	"github.com/team09/app/ent/predicate"
	"github.com/team09/app/ent/workingtime"
)

// WorkingtimeUpdate is the builder for updating Workingtime entities.
type WorkingtimeUpdate struct {
	config
	hooks      []Hook
	mutation   *WorkingtimeMutation
	predicates []predicate.Workingtime
}

// Where adds a new predicate for the builder.
func (wu *WorkingtimeUpdate) Where(ps ...predicate.Workingtime) *WorkingtimeUpdate {
	wu.predicates = append(wu.predicates, ps...)
	return wu
}

// SetAddedTime sets the added_time field.
func (wu *WorkingtimeUpdate) SetAddedTime(t time.Time) *WorkingtimeUpdate {
	wu.mutation.SetAddedTime(t)
	return wu
}

// AddDoctorIDs adds the doctors edge to Doctor by ids.
func (wu *WorkingtimeUpdate) AddDoctorIDs(ids ...int) *WorkingtimeUpdate {
	wu.mutation.AddDoctorIDs(ids...)
	return wu
}

// AddDoctors adds the doctors edges to Doctor.
func (wu *WorkingtimeUpdate) AddDoctors(d ...*Doctor) *WorkingtimeUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return wu.AddDoctorIDs(ids...)
}

// Mutation returns the WorkingtimeMutation object of the builder.
func (wu *WorkingtimeUpdate) Mutation() *WorkingtimeMutation {
	return wu.mutation
}

// RemoveDoctorIDs removes the doctors edge to Doctor by ids.
func (wu *WorkingtimeUpdate) RemoveDoctorIDs(ids ...int) *WorkingtimeUpdate {
	wu.mutation.RemoveDoctorIDs(ids...)
	return wu
}

// RemoveDoctors removes doctors edges to Doctor.
func (wu *WorkingtimeUpdate) RemoveDoctors(d ...*Doctor) *WorkingtimeUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return wu.RemoveDoctorIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (wu *WorkingtimeUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(wu.hooks) == 0 {
		affected, err = wu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WorkingtimeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wu.mutation = mutation
			affected, err = wu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wu.hooks) - 1; i >= 0; i-- {
			mut = wu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WorkingtimeUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WorkingtimeUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WorkingtimeUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wu *WorkingtimeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   workingtime.Table,
			Columns: workingtime.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: workingtime.FieldID,
			},
		},
	}
	if ps := wu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.AddedTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: workingtime.FieldAddedTime,
		})
	}
	if nodes := wu.mutation.RemovedDoctorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workingtime.DoctorsTable,
			Columns: []string{workingtime.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.DoctorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workingtime.DoctorsTable,
			Columns: []string{workingtime.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workingtime.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// WorkingtimeUpdateOne is the builder for updating a single Workingtime entity.
type WorkingtimeUpdateOne struct {
	config
	hooks    []Hook
	mutation *WorkingtimeMutation
}

// SetAddedTime sets the added_time field.
func (wuo *WorkingtimeUpdateOne) SetAddedTime(t time.Time) *WorkingtimeUpdateOne {
	wuo.mutation.SetAddedTime(t)
	return wuo
}

// AddDoctorIDs adds the doctors edge to Doctor by ids.
func (wuo *WorkingtimeUpdateOne) AddDoctorIDs(ids ...int) *WorkingtimeUpdateOne {
	wuo.mutation.AddDoctorIDs(ids...)
	return wuo
}

// AddDoctors adds the doctors edges to Doctor.
func (wuo *WorkingtimeUpdateOne) AddDoctors(d ...*Doctor) *WorkingtimeUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return wuo.AddDoctorIDs(ids...)
}

// Mutation returns the WorkingtimeMutation object of the builder.
func (wuo *WorkingtimeUpdateOne) Mutation() *WorkingtimeMutation {
	return wuo.mutation
}

// RemoveDoctorIDs removes the doctors edge to Doctor by ids.
func (wuo *WorkingtimeUpdateOne) RemoveDoctorIDs(ids ...int) *WorkingtimeUpdateOne {
	wuo.mutation.RemoveDoctorIDs(ids...)
	return wuo
}

// RemoveDoctors removes doctors edges to Doctor.
func (wuo *WorkingtimeUpdateOne) RemoveDoctors(d ...*Doctor) *WorkingtimeUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return wuo.RemoveDoctorIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (wuo *WorkingtimeUpdateOne) Save(ctx context.Context) (*Workingtime, error) {

	var (
		err  error
		node *Workingtime
	)
	if len(wuo.hooks) == 0 {
		node, err = wuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WorkingtimeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wuo.mutation = mutation
			node, err = wuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(wuo.hooks) - 1; i >= 0; i-- {
			mut = wuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WorkingtimeUpdateOne) SaveX(ctx context.Context) *Workingtime {
	w, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return w
}

// Exec executes the query on the entity.
func (wuo *WorkingtimeUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WorkingtimeUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wuo *WorkingtimeUpdateOne) sqlSave(ctx context.Context) (w *Workingtime, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   workingtime.Table,
			Columns: workingtime.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: workingtime.FieldID,
			},
		},
	}
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Workingtime.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := wuo.mutation.AddedTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: workingtime.FieldAddedTime,
		})
	}
	if nodes := wuo.mutation.RemovedDoctorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workingtime.DoctorsTable,
			Columns: []string{workingtime.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.DoctorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workingtime.DoctorsTable,
			Columns: []string{workingtime.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	w = &Workingtime{config: wuo.config}
	_spec.Assign = w.assignValues
	_spec.ScanValues = w.scanValues()
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workingtime.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return w, nil
}
