/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntTraining,
    EntTrainingFromJSON,
    EntTrainingFromJSONTyped,
    EntTrainingToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCourseEdges
 */
export interface EntCourseEdges {
    /**
     * Trainings holds the value of the trainings edge.
     * @type {Array<EntTraining>}
     * @memberof EntCourseEdges
     */
    trainings?: Array<EntTraining>;
}

export function EntCourseEdgesFromJSON(json: any): EntCourseEdges {
    return EntCourseEdgesFromJSONTyped(json, false);
}

export function EntCourseEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCourseEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'trainings': !exists(json, 'trainings') ? undefined : ((json['trainings'] as Array<any>).map(EntTrainingFromJSON)),
    };
}

export function EntCourseEdgesToJSON(value?: EntCourseEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'trainings': value.trainings === undefined ? undefined : ((value.trainings as Array<any>).map(EntTrainingToJSON)),
    };
}


