/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntOfficeEdges,
    EntOfficeEdgesFromJSON,
    EntOfficeEdgesFromJSONTyped,
    EntOfficeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntOffice
 */
export interface EntOffice {
    /**
     * Doctoridcard holds the value of the "doctoridcard" field.
     * @type {string}
     * @memberof EntOffice
     */
    doctoridcard?: string;
    /**
     * 
     * @type {EntOfficeEdges}
     * @memberof EntOffice
     */
    edges?: EntOfficeEdges;
    /**
     * Finallytime holds the value of the "finallytime" field.
     * @type {string}
     * @memberof EntOffice
     */
    finallytime?: string;
    /**
     * Firsttime holds the value of the "firsttime" field.
     * @type {string}
     * @memberof EntOffice
     */
    firsttime?: string;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntOffice
     */
    id?: number;
    /**
     * Officename holds the value of the "officename" field.
     * @type {string}
     * @memberof EntOffice
     */
    officename?: string;
    /**
     * Roomnumber holds the value of the "roomnumber" field.
     * @type {string}
     * @memberof EntOffice
     */
    roomnumber?: string;
}

export function EntOfficeFromJSON(json: any): EntOffice {
    return EntOfficeFromJSONTyped(json, false);
}

export function EntOfficeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntOffice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doctoridcard': !exists(json, 'doctoridcard') ? undefined : json['doctoridcard'],
        'edges': !exists(json, 'edges') ? undefined : EntOfficeEdgesFromJSON(json['edges']),
        'finallytime': !exists(json, 'finallytime') ? undefined : json['finallytime'],
        'firsttime': !exists(json, 'firsttime') ? undefined : json['firsttime'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'officename': !exists(json, 'officename') ? undefined : json['officename'],
        'roomnumber': !exists(json, 'roomnumber') ? undefined : json['roomnumber'],
    };
}

export function EntOfficeToJSON(value?: EntOffice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doctoridcard': value.doctoridcard,
        'edges': EntOfficeEdgesToJSON(value.edges),
        'finallytime': value.finallytime,
        'firsttime': value.firsttime,
        'id': value.id,
        'officename': value.officename,
        'roomnumber': value.roomnumber,
    };
}


