/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDepartment,
    EntDepartmentFromJSON,
    EntDepartmentFromJSONTyped,
    EntDepartmentToJSON,
    EntDoctor,
    EntDoctorFromJSON,
    EntDoctorFromJSONTyped,
    EntDoctorToJSON,
    EntSchedule,
    EntScheduleFromJSON,
    EntScheduleFromJSONTyped,
    EntScheduleToJSON,
    EntSpecialist,
    EntSpecialistFromJSON,
    EntSpecialistFromJSONTyped,
    EntSpecialistToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntOfficeEdges
 */
export interface EntOfficeEdges {
    /**
     * 
     * @type {EntDepartment}
     * @memberof EntOfficeEdges
     */
    department?: EntDepartment;
    /**
     * 
     * @type {EntDoctor}
     * @memberof EntOfficeEdges
     */
    doctor?: EntDoctor;
    /**
     * Schedules holds the value of the schedules edge.
     * @type {Array<EntSchedule>}
     * @memberof EntOfficeEdges
     */
    schedules?: Array<EntSchedule>;
    /**
     * 
     * @type {EntSpecialist}
     * @memberof EntOfficeEdges
     */
    specialist?: EntSpecialist;
}

export function EntOfficeEdgesFromJSON(json: any): EntOfficeEdges {
    return EntOfficeEdgesFromJSONTyped(json, false);
}

export function EntOfficeEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntOfficeEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'department': !exists(json, 'department') ? undefined : EntDepartmentFromJSON(json['department']),
        'doctor': !exists(json, 'doctor') ? undefined : EntDoctorFromJSON(json['doctor']),
        'schedules': !exists(json, 'schedules') ? undefined : ((json['schedules'] as Array<any>).map(EntScheduleFromJSON)),
        'specialist': !exists(json, 'specialist') ? undefined : EntSpecialistFromJSON(json['specialist']),
    };
}

export function EntOfficeEdgesToJSON(value?: EntOfficeEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'department': EntDepartmentToJSON(value.department),
        'doctor': EntDoctorToJSON(value.doctor),
        'schedules': value.schedules === undefined ? undefined : ((value.schedules as Array<any>).map(EntScheduleToJSON)),
        'specialist': EntSpecialistToJSON(value.specialist),
    };
}


